name: publish

on:
  workflow_run:
    workflows: ["front-linter"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build the React App
        run: npm run build:prod

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t react-app .

      - name: Tag Docker image
        run: docker tag react-app ${{ secrets.DOCKER_USERNAME }}/react-app:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          ssh -i <(echo "$SSH_PRIVATE_KEY") -o StrictHostKeyChecking=no "$VPS_USER@$VPS_HOST" << 'EOF'
            docker pull $DOCKER_USERNAME/react-app:latest
            docker stop react-app || true
            docker rm react-app || true
            docker run -d -p 80:5000 --name react-app $DOCKER_USERNAME/react-app:latest
          EOF
