name: publish

on:
  workflow_run:
    workflows: ["front-linter"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the React App
        run: npm run build:prod

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to VPS
    needs: build

    steps:
      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} > ~/.ssh/known_hosts
      - name: Connect and pull
        run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "docker pull ${{ secrets.DOCKER_USERNAME }}/react-app:latest && docker stop react-app || true && docker rm react-app || true && docker run -d -p 3031:80 -e VITE_APP_NAME=${{ secrets.VITE_APP_NAME }} -e VITE_BACKEND_ENDPOINT=${{ secrets.VITE_BACKEND_ENDPOINT }} --name react-auth-container ${{ secrets.DOCKER_USERNAME }}/react-app:latest"

      - name: Clean SSH key
        run: rm -rf ~/.ssh
